import type { Metadata } from "next";

import Header from "app/components/shared/header";
import NavBar from "app/components/shared/nav";
import Footer from "app/components/shared/footer";

import "./globals.css";
import TituloPrincipal from "app/components/pagina-principal/TituloPrincipal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex items-center flex-col">
        <Header />
        <NavBar />
        <main className="flex flex-col max-w-7xl w-full justify-center items-center p-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
