import { Metadata } from "next";
import { LayoutProps } from "../../../.next/types/app/layout";
import { Filtros } from "app/components/shared/filtros/Filtros";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function layout(props: LayoutProps) {

    return (
        <main className="w-full flex justify-center">
            <div className="flex flex-row max-w-7xl w-full justify-center">
                {props.children}
            </div>
        </main>

    );
}