import { Metadata } from "next";
import { LayoutProps } from "../../../.next/types/app/layout";
import { Filtros } from "app/components/shared/filtros/Filtros";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function layout(props: LayoutProps) {

    return (
        <main>
            <Filtros />
            <section>
                {props.children}
            </section>
        </main>
    );
}